import SidebarComponent from "@/components/SidebarComponent";
import "../globals.css";
import TodoList from "./todo-list/page";
import NavbarComponent from "@/components/NavbarComponent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (

     
        <div>
          <div className="flex gap-24">
            <div>
              <SidebarComponent />
            </div>
            <div className="w-full">
              <NavbarComponent />
              <div className="my-2">
                {children}
              </div>
            </div>
          </div>
        </div>
     
  
  );
}
